apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        image: nguyenson255/todosocket-be
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: '3001'
        - name: DATABASE_PASSWORD
          value: ns
        - name: BASE_URL
          value: api
        - name: DATABASE_HOST
          value: postgres-service

---
apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: be
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: LoadBalancer

        
